common: &default_settings
  monitor_mode: true
  log_level: info
  log_file_path: STDOUT
  transaction_tracer:
    enabled: false
  error_collector:
    enabled: true
development:
  <<: *default_settings
  monitor_mode: false
test:
  <<: *default_settings
  monitor_mode: true
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
