common: &default_settings
  monitor_mode: true
  developer_mode: false
  log_level: info
  log_file_path: STDOUT
  ssl: false
  apdex_t: 0.25
  capture_params: false
  transaction_tracer:
    enabled: false
  error_collector:
    enabled: true
development:
  <<: *default_settings
  monitor_mode: false
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
